In [1]:
import pandas as pd

In [2]:
xbox=pd.read_csv(r"C:\Users\Rahhal\Desktop\DataSets\CSV Data\XboxOne_GameSales.csv")

In [3]:
xbox

,Pos,Game,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global
0,1,Grand Theft Auto V,2014.0,Action,Rockstar Games,4.70,3.25,0.01,0.76,8.72
1,2,Call of Duty: Black Ops 3,2015.0,Shooter,Activision,4.63,2.04,0.02,0.68,7.37
2,3,Call of Duty: WWII,2017.0,Shooter,Activision,3.75,1.91,0.00,0.57,6.23
3,4,Red Dead Redemption 2,2018.0,Action-Adventure,Rockstar Games,3.76,1.47,0.00,0.54,5.77
4,5,MineCraft,2014.0,Misc,Microsoft Studios,3.23,1.71,0.00,0.49,5.43
...,...,...,...,...,...,...,...,...,...,...
608,609,Biomutant,2018.0,Action,THQ Nordic,0.00,0.00,0.00,0.00,0.00
609,610,Biomutant,2019.0,Action,THQ Nordic,0.00,0.00,0.00,0.00,0.00
610,611,de Blob,2017.0,Platform,THQ Nordic,0.00,0.00,0.00,0.00,0.00
611,612,Outcast: Second Contact,2017.0,Adventure,Bigben Interactive,0.00,0.00,0.00,0.00,0.00
612,613,Code Vein,2019.0,Action,Bandai Namco Entertainment,0.00,0.00,0.00,0.00,0.00

## Displayed all Data

In [26]:
pd.options.display.max_rows=613

In [27]:
xbox

,Pos,Game,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global
0,1,Grand Theft Auto V,2014.0,Action,Rockstar Games,4.70,3.25,0.01,0.76,8.72
1,2,Call of Duty: Black Ops 3,2015.0,Shooter,Activision,4.63,2.04,0.02,0.68,7.37
2,3,Call of Duty: WWII,2017.0,Shooter,Activision,3.75,1.91,0.00,0.57,6.23
3,4,Red Dead Redemption 2,2018.0,Action-Adventure,Rockstar Games,3.76,1.47,0.00,0.54,5.77
4,5,MineCraft,2014.0,Misc,Microsoft Studios,3.23,1.71,0.00,0.49,5.43
5,6,Call of Duty: Advanced Warfare,2014.0,Shooter,Activision,3.25,1.49,0.01,0.48,5.22
6,7,Battlefield 1,2016.0,Shooter,Electronic Arts,3.37,1.26,0.02,0.48,5.13
7,8,Fallout 4,2015.0,Role-Playing,Bethesda Softworks,2.94,1.62,0.02,0.45,5.03
8,9,Halo 5: Guardians,2015.0,Shooter,Microsoft Studios,2.94,1.49,0.03,0.45,4.92
9,10,Call of Duty: Infinite Warfare,2016.0,Shooter,Activision,2.91,1.44,0.00,0.44,4.79
10,11,Star Wars Battlefront (2015),2015.0,Shooter,Electronic Arts,2.49,1.26,0.02,0.38,4.15
11,12,Forza Horizon 3,2016.0,Racing,Microsoft Studios,1.64,1.96,0.02,0.32,3.93
12,13,FIFA 17,2016.0,Sports,Electronic Arts,1.04,2.40,0.00,0.27,3.71
13,14,Gears of War: Ultimate Edition,2015.0,Shooter,Microsoft Studios,2.88,0.37,0.00,0.37,3.62
14,15,Assassin's Creed: Unity,2014.0,Action,Ubisoft,2.34,0.90,0.00,0.34,3.58
15,16,Halo: The Master Chief Collection,2014.0,Shooter,Microsoft Studios,2.06,1.04,0.03,0.31,3.44
16,17,Destiny,2014.0,Shooter,Activision,2.17,0.92,0.00,0.32,3.41
17,18,Gears of War 4,2016.0,Shooter,Microsoft Studios,2.17,0.90,0.00,0.32,3.38
18,19,FIFA 16,2015.0,Sports,EA Sports,0.92,2.10,0.00,0.24,3.25
19,20,FIFA 18,2017.0,Sports,EA Sports,0.98,1.92,0.00,0.23,3.14
20,21,Titanfall,2014.0,Shooter,Electronic Arts,1.88,0.91,0.04,0.28,3.11
21,22,Call of Duty: Ghosts,2013.0,Shooter,Activision,1.92,0.86,0.00,0.28,3.07
22,23,Overwatch,2016.0,Shooter,Blizzard Entertainment,1.63,0.84,0.00,0.25,2.72
23,24,Tom Clancy's Rainbow Six: Siege,2015.0,Shooter,Ubisoft,1.62,0.84,0.00,0.25,2.71
24,25,Tom Clancy's The Division,2016.0,Shooter,Ubisoft,1.54,0.82,0.00,0.24,2.59
25,26,Assassin's Creed Origins,2017.0,Action,Ubisoft,1.34,0.92,0.00,0.22,2.47
26,27,Madden NFL 16,2015.0,Sports,EA Sports,2.13,0.08,0.00,0.26,2.47
27,28,Madden NFL 17,2016.0,Sports,EA Sports,2.14,0.04,0.00,0.26,2.44
28,29,NBA 2K16,2015.0,Sports,2K Sports,2.01,0.15,0.00,0.25,2.41
29,30,Forza Motorsport 5,2013.0,Racing,Microsoft Studios,1.28,0.90,0.01,0.21,2.40
30,31,Destiny 2,2017.0,Shooter,Activision,1.66,0.47,0.00,0.23,2.35
31,32,Assassin's Creed IV: Black Flag,2013.0,Action,Ubisoft,1.51,0.59,0.00,0.22,2.32
32,33,FIFA 15,2014.0,Sports,EA Sports,0.64,1.39,0.00,0.16,2.19
33,34,PlayerUnknown's Battlegrounds,2017.0,Shooter,Microsoft Studios,1.29,0.69,0.00,0.20,2.17
34,35,Battlefield 4,2013.0,Shooter,Electronic Arts,1.26,0.65,0.00,0.19,2.09
35,36,NBA 2K17,2016.0,Sports,2K Sports,1.70,0.12,0.00,0.21,2.04
36,37,Forza Motorsport 6,2015.0,Racing,Microsoft Studios,0.90,0.92,0.04,0.16,2.02
37,38,NBA 2K18,2017.0,Sports,2K Sports,1.67,0.14,0.00,0.21,2.02
38,39,Star Wars Battlefront II (2017),2017.0,Shooter,Electronic Arts,1.15,0.59,0.00,0.17,1.92
39,40,Madden NFL 18,2017.0,Sports,EA Sports,1.63,0.07,0.00,0.20,1.91
40,41,The Elder Scrolls V: Skyrim,2016.0,Role-Playing,Bethesda Softworks,1.13,0.53,0.00,0.17,1.83
41,42,Far Cry 5,2018.0,Action,Ubisoft,1.14,0.47,0.00,0.17,1.78
42,43,Mortal Kombat X,2015.0,Fighting,Warner Bros. Interactive Entertainment,1.34,0.23,0.00,0.18,1.74
43,44,NBA 2K15,2014.0,Sports,2K Sports,1.39,0.18,0.00,0.18,1.74
44,45,The Witcher 3: Wild Hunt,2015.0,Role-Playing,Namco Bandai Games,0.97,0.61,0.01,0.15,1.74
45,46,Far Cry 4,2014.0,Shooter,Ubisoft,0.85,0.68,0.02,0.14,1.68
46,47,Watch Dogs,2014.0,Action-Adventure,Ubisoft,0.91,0.59,0.00,0.15,1.64
47,48,Dead Rising 3,2013.0,Action,Microsoft Studios,1.06,0.40,0.01,0.15,1.63
48,49,Tom Clancy's Ghost Recon Wildlands,2017.0,Shooter,Ubisoft,0.98,0.48,0.00,0.15,1.61
49,50,Madden NFL 15,2014.0,Sports,EA Sports,1.34,0.10,0.00,0.17,1.60
50,51,Rise of the Tomb Raider,2015.0,Adventure,Square Enix,0.61,0.82,0.03,0.12,1.58
51,52,Batman: Arkham Knight,2015.0,Action,Warner Bros. Interactive Entertainment,0.97,0.46,0.00,0.14,1.58
52,53,Forza Motorsport 7,2017.0,Racing,Microsoft Studios,0.58,0.81,0.01,0.12,1.52
53,54,Dying Light,2015.0,Action,Warner Bros. Interactive Entertainment,1.01,0.31,0.01,0.14,1.47
54,55,Ryse,2013.0,Action,Microsoft Studios,0.84,0.49,0.00,0.13,1.47
55,56,Forza Horizon 2,2014.0,Racing,Microsoft Studios,0.56,0.79,0.01,0.11,1.46
56,57,Doom (2016),2016.0,Shooter,Bethesda Softworks,0.76,0.57,0.00,0.13,1.45
57,58,Assassin's Creed Syndicate,2015.0,Action,Ubisoft,0.71,0.61,0.00,0.12,1.44
58,59,Middle-Earth: Shadow of Mordor,2014.0,Action,Warner Bros. Interactive Entertainment,0.77,0.52,0.01,0.12,1.42
59,60,Rocket League,2016.0,Sports,505 Games,0.52,0.75,0.00,0.11,1.38
60,61,The Elder Scrolls Online,2015.0,MMO,Bethesda Softworks,0.86,0.39,0.00,0.13,1.38
61,62,Titanfall 2,2016.0,Shooter,Electronic Arts,0.88,0.37,0.00,0.13,1.37
62,63,Watch Dogs 2,2016.0,Action,Ubisoft,0.71,0.53,0.00,0.12,1.35
63,64,FIFA Soccer 14,2013.0,Sports,EA Sports,0.44,0.78,0.00,0.10,1.31
64,65,Destiny: The Taken King,2015.0,Shooter,Activision,0.91,0.23,0.00,0.12,1.27
65,66,Battlefield: Hardline,2015.0,Shooter,Electronic Arts,0.73,0.39,0.01,0.11,1.24
66,67,Sunset Overdrive,2014.0,Action,Microsoft Studios,0.64,0.42,0.00,0.10,1.16
67,68,Middle-Earth: Shadow of War,2017.0,Action,Warner Bros. Interactive Entertainment,0.75,0.29,0.00,0.11,1.15
68,69,Lego Marvel Super Heroes,2013.0,Action,Warner Bros. Interactive Entertainment,0.61,0.44,0.00,0.10,1.15
69,70,Final Fantasy XV,2016.0,Role-Playing,Square Enix,0.72,0.30,0.01,0.11,1.14
70,71,Mafia III,2016.0,Action-Adventure,2K Games,0.54,0.48,0.00,0.09,1.11
71,72,Diablo III,2014.0,Role-Playing,Blizzard Entertainment,0.62,0.32,0.00,0.09,1.04
72,73,Just Cause 3,2015.0,Action-Adventure,Square Enix,0.52,0.41,0.00,0.09,1.01
73,74,Far Cry: Primal,2016.0,Action-Adventure,Ubisoft,0.51,0.41,0.00,0.09,1.00
74,75,Dragon Age III: Inquisition,2014.0,Role-Playing,Electronic Arts,0.63,0.27,0.00,0.09,0.99
75,76,Sea of Thieves,2018.0,Action-Adventure,Microsoft Studios,0.60,0.27,0.00,0.09,0.96
76,77,NBA 2K14,2013.0,Sports,2K Sports,0.72,0.12,0.00,0.09,0.94
77,78,Monster Hunter: World,2018.0,Action,Capcom,0.67,0.17,0.00,0.09,0.93
78,79,Injustice 2,2017.0,Fighting,Warner Bros. Interactive Entertainment,0.65,0.16,0.00,0.09,0.89
79,80,Resident Evil VII: Biohazard,2017.0,Action,Capcom,0.51,0.30,0.00,0.08,0.89
80,81,For Honor,2017.0,Action,Ubisoft,0.57,0.21,0.00,0.08,0.87
81,82,Dishonored 2,2016.0,Action,Bethesda Softworks,0.47,0.31,0.00,0.08,0.86
82,83,Plants vs. Zombies: Garden Warfare 2,2016.0,Shooter,Electronic Arts,0.47,0.32,0.00,0.08,0.86
83,84,Madden NFL 25,2013.0,Sports,EA Sports,0.69,0.06,0.00,0.09,0.83
84,85,Metal Gear Solid V: The Phantom Pain,2015.0,Action,Konami Digital Entertainment,0.49,0.25,0.02,0.07,0.83
85,86,Guitar Hero Live,2015.0,Music,Activision,0.52,0.23,0.00,0.08,0.83
86,87,Dark Souls III,2016.0,Role-Playing,Namco Bandai Games,0.56,0.15,0.00,0.08,0.79
87,88,LEGO Jurassic World,2015.0,Action,Warner Bros. Interactive Entertainment,0.44,0.27,0.00,0.07,0.78
88,89,Rare Replay,2015.0,Misc,Microsoft Studios,0.42,0.27,0.01,0.07,0.78
89,90,Mass Effect: Andromeda,2017.0,Role-Playing,Electronic Arts,0.50,0.20,0.00,0.07,0.78
90,91,Minecraft: Story Mode,2015.0,Adventure,Mojang,0.46,0.24,0.00,0.07,0.77
91,92,Fortnite,2017.0,Action,Gearbox Software,0.60,0.09,0.00,0.08,0.77
92,93,Quantum Break,2016.0,Action,Microsoft Studios,0.42,0.25,0.02,0.07,0.76
93,94,Wolfenstein: The New Order,2014.0,Shooter,Bethesda Softworks,0.39,0.30,0.00,0.06,0.75
94,95,Rock Band 4,2015.0,Music,Harmonix Music Systems,0.62,0.05,0.00,0.08,0.75
95,96,Need for Speed (2015),2015.0,Racing,Electronic Arts,0.35,0.33,0.00,0.06,0.74
96,97,The Sims 4,2017.0,Simulation,Electronic Arts,0.42,0.24,0.00,0.07,0.73
97,98,Need for Speed: Payback,2017.0,Racing,Electronic Arts,0.42,0.24,0.00,0.07,0.73
98,99,Dead Rising 4,2016.0,Action-Adventure,Microsoft Studios,0.41,0.25,0.00,0.06,0.73
99,100,LEGO Dimensions,2015.0,Action,Warner Bros. Interactive Entertainment,0.47,0.18,0.00,0.07,0.72
100,101,The Crew,2014.0,Racing,Ubisoft,0.32,0.34,0.00,0.06,0.71
101,102,Plants vs Zombies: Garden Warfare,2014.0,Shooter,Electronic Arts,0.39,0.25,0.00,0.06,0.71
102,103,Need for Speed Rivals,2013.0,Racing,Electronic Arts,0.45,0.19,0.00,0.07,0.70
103,104,Wolfenstein II: The New Colossus,2017.0,Shooter,Bethesda Softworks,0.45,0.19,0.00,0.07,0.70
104,105,The Evil Within,2014.0,Misc,Bethesda Softworks,0.36,0.27,0.00,0.06,0.69
105,106,LEGO Worlds,2017.0,Misc,Warner Bros. Interactive Entertainment,0.28,0.35,0.00,0.05,0.69
106,107,Borderlands: The Handsome Collection,2015.0,Shooter,2K Games,0.49,0.13,0.00,0.07,0.68
107,108,Evolve,2015.0,Shooter,2K Games,0.40,0.20,0.00,0.06,0.67
108,109,WWE 2K18,2017.0,Sports,2K Sports,0.35,0.25,0.00,0.06,0.66
109,110,Tomb Raider (2013),2014.0,Action-Adventure,Square Enix,0.38,0.22,0.00,0.06,0.66
110,111,The LEGO Movie Videogame,2014.0,Action-Adventure,Warner Bros. Interactive Entertainment,0.42,0.17,0.00,0.06,0.65
111,112,WWE 2K16,2015.0,Sports,Take-Two Interactive,0.34,0.24,0.00,0.06,0.63
112,113,Kinect Sports Rivals,2014.0,Sports,Microsoft Studios,0.30,0.25,0.02,0.05,0.62
113,114,South Park: The Fractured But Whole,2017.0,Role-Playing,Ubisoft,0.40,0.17,0.00,0.06,0.62
114,115,WWE 2K15,2014.0,Sports,2K Sports,0.32,0.23,0.00,0.05,0.61
115,116,EA Sports UFC 2,2016.0,Sports,EA Sports,0.36,0.19,0.00,0.06,0.61
116,117,NHL 17,2016.0,Sports,EA Sports,0.52,0.01,0.00,0.06,0.60
117,118,Tekken 7,2017.0,Fighting,Namco Bandai Games,0.30,0.23,0.00,0.05,0.58
118,119,LEGO Marvel Super Heroes 2,2017.0,Action,Warner Bros. Interactive Entertainment,0.32,0.20,0.00,0.05,0.57
119,120,WWE 2K17,2016.0,Sports,2K Games,0.26,0.26,0.00,0.05,0.57
120,121,Disney Infinity 2.0: Marvel Super Heroes,2014.0,Action-Adventure,Disney Interactive Studios,0.35,0.15,0.00,0.05,0.55
121,122,Just Dance 2015,2014.0,Music,Ubisoft,0.36,0.13,0.00,0.05,0.54
122,123,Dragon Ball Fighter Z,2018.0,Fighting,Namco Bandai Games,0.38,0.09,0.00,0.05,0.52
123,124,Alien: Isolation,2014.0,Adventure,Sega,0.23,0.25,0.00,0.04,0.52
124,125,Halo Wars 2,2017.0,Strategy,Microsoft Studios,0.31,0.15,0.00,0.05,0.51
125,126,NHL 16,2015.0,Sports,EA Sports,0.41,0.05,0.00,0.05,0.51
126,127,Lego Star Wars: The Force Awakens,2016.0,Action-Adventure,Warner Bros. Interactive Entertainment,0.24,0.22,0.00,0.04,0.50
127,128,Mad Max (2013),2015.0,Action,Warner Bros. Interactive Entertainment,0.29,0.16,0.00,0.05,0.50
128,129,LEGO Marvel's Avengers,2016.0,Action,Warner Bros. Interactive Entertainment,0.26,0.18,0.00,0.04,0.48
129,130,Zoo Tycoon (2013),2013.0,Simulation,Microsoft Studios,0.25,0.18,0.00,0.04,0.48
130,131,Steep,2016.0,Sports,Ubisoft,0.24,0.20,0.00,0.04,0.48
131,132,Thief 4,2014.0,Action,Square Enix,0.26,0.17,0.00,0.04,0.48
132,133,Just Dance 2014,2013.0,Music,Ubisoft,0.31,0.12,0.00,0.04,0.48
133,134,EA Sports UFC,2014.0,Fighting,Electronic Arts,0.30,0.13,0.00,0.04,0.48
134,135,BioShock The Collection,2016.0,Shooter,2K Games,0.35,0.08,0.00,0.05,0.48
135,136,Dragon Ball: Xenoverse 2,2016.0,Action,Namco Bandai Games,0.33,0.09,0.00,0.05,0.47
136,137,ARK: Survival Evolved,2017.0,Action-Adventure,Studio Wildcard,0.30,0.12,0.00,0.04,0.46
137,138,Disney Infinity 3.0,2015.0,Action,Disney Interactive Studios,0.30,0.12,0.00,0.04,0.46
138,139,Prey (2017),2017.0,Shooter,Bethesda Softworks,0.21,0.20,0.00,0.04,0.45
139,140,Skylanders: Trap Team,2014.0,Platform,Activision,0.34,0.07,0.00,0.04,0.45
140,141,Lego Batman 3: Beyond Gotham,2014.0,Action,Warner Bros. Interactive Entertainment,0.24,0.17,0.00,0.04,0.44
141,142,EA Sports UFC 3,2018.0,Sports,EA Sports,0.30,0.10,0.00,0.04,0.44
142,143,Rocksmith 2014,2014.0,Music,Ubisoft,0.31,0.08,0.00,0.04,0.43
143,144,Sniper Elite 3,2014.0,Shooter,505 Games,0.27,0.12,0.00,0.04,0.43
144,145,Hello Neighbor,2017.0,Action,Gearbox Software,0.27,0.11,0.00,0.04,0.42
145,146,NHL 15,2014.0,Sports,EA Sports,0.32,0.06,0.00,0.04,0.42
146,147,Project CARS,2015.0,Racing,Bandai Namco Games,0.21,0.16,0.00,0.04,0.41
147,148,Destiny: The Collection,2016.0,Shooter,Activision,0.25,0.12,0.00,0.04,0.41
148,149,Skylanders: SuperChargers,2015.0,Action-Adventure,Activision,0.31,0.05,0.00,0.04,0.40
149,150,Deus Ex: Mankind Divided,2016.0,Role-Playing,Square Enix,0.25,0.11,0.00,0.04,0.39
150,151,NHL 18,2017.0,Sports,EA Sports,0.32,0.03,0.00,0.04,0.39
151,152,The Evil Within II,2017.0,Action,Bethesda Softworks,0.25,0.10,0.00,0.04,0.39
152,153,Rayman Legends,2014.0,Platform,Ubisoft,0.13,0.22,0.00,0.03,0.38
153,154,Just Dance 2016,2015.0,Music,Ubisoft,0.30,0.04,0.00,0.04,0.38
154,155,Skylanders SWAP Force,2013.0,Misc,Activision,0.25,0.07,0.00,0.03,0.35
155,156,Naruto Shippuden: Ultimate Ninja Storm 4,2016.0,Fighting,Namco Bandai Games,0.25,0.07,0.00,0.03,0.35
156,157,Dragon Ball: XenoVerse,2015.0,Fighting,Namco Bandai Games,0.21,0.11,0.00,0.03,0.35
157,158,Marvel vs. Capcom: Infinite,2017.0,Fighting,Capcom,0.26,0.05,0.00,0.03,0.34
158,159,Just Dance 2017,2016.0,Music,Ubisoft,0.25,0.05,0.00,0.03,0.34
159,160,The Lego Ninjago Movie Videogame,2017.0,Action,Warner Bros. Interactive Entertainment,0.21,0.09,0.00,0.03,0.33
160,161,The Crew 2,2018.0,Racing,Ubisoft,0.20,0.10,0.00,0.03,0.33
161,162,Farming Simulator 17,2016.0,Simulation,Focus Home Interactive,0.19,0.11,0.00,0.03,0.33
162,163,METRO 2033,2014.0,Shooter,Deep Silver,0.15,0.14,0.00,0.03,0.31
163,164,Hitman (2016),2017.0,Action,Square Enix,0.20,0.08,0.00,0.03,0.31
164,165,LEGO City Undercover,2017.0,Platform,Warner Bros. Interactive Entertainment,0.15,0.12,0.00,0.03,0.30
165,166,Final Fantasy Type-0,2015.0,Role-Playing,Square Enix,0.20,0.07,0.00,0.03,0.30
166,167,Sniper Elite 4,2017.0,Shooter,Rebellion Developments,0.18,0.09,0.00,0.03,0.30
167,168,Sonic Forces,2017.0,Platform,Sega,0.15,0.11,0.00,0.03,0.29
168,169,Dark Souls II,2015.0,Role-Playing,Namco Bandai Games,0.19,0.07,0.00,0.03,0.28
169,170,Battleborn,2016.0,Shooter,2K Games,0.20,0.05,0.00,0.03,0.28
170,171,Rory McIlroy PGA Tour,2015.0,Sports,Electronic Arts,0.16,0.09,0.00,0.02,0.28
171,172,Assassin's Creed The Ezio Collection,2016.0,Action,Ubisoft,0.13,0.12,0.00,0.02,0.27
172,173,LEGO The Hobbit,2014.0,Action-Adventure,Warner Bros. Interactive Entertainment,0.13,0.13,0.00,0.02,0.27
173,174,Metal Gear Solid: Ground Zeroes,2014.0,Action-Adventure,Konami Digital Entertainment,0.13,0.13,0.00,0.02,0.27
174,175,Minecraft: Story Mode - Season Two,2017.0,Adventure,Telltale Games,0.17,0.08,0.00,0.02,0.27
175,176,Skylanders Imaginators,2016.0,Platform,Activision,0.19,0.05,0.00,0.03,0.27
176,177,Friday the 13th: The Game,2017.0,Action,Gun Media,0.21,0.03,0.00,0.03,0.27
177,178,ReCore,2016.0,Action-Adventure,Microsoft Studios,0.16,0.06,0.01,0.02,0.26
178,179,F1 2015,2015.0,Racing,Codemasters,0.09,0.15,0.00,0.02,0.25
179,180,L.A. Noire,2017.0,Adventure,Rockstar Games,0.14,0.09,0.00,0.02,0.25
180,181,Trials Fusion,2014.0,Racing,Ubisoft,0.12,0.10,0.00,0.02,0.25
181,182,Call of Duty: Modern Warfare Remastered,2017.0,Shooter,Activision,0.16,0.06,0.00,0.02,0.24
182,183,Zumba Fitness: World Party,2013.0,Misc,Majesco Entertainment,0.17,0.05,0.00,0.02,0.24
183,184,Saints Row IV,2015.0,Action,Deep Silver,0.13,0.09,0.00,0.02,0.24
184,185,Farming Simulator 2015,2015.0,Simulation,Koch Media,0.13,0.09,0.00,0.02,0.24
185,186,A Way Out,2018.0,Action,Electronic Arts,0.17,0.05,0.00,0.02,0.24
186,187,NBA Live 14,2013.0,Sports,EA Sports,0.19,0.02,0.00,0.02,0.24
187,188,Payday 2,2015.0,Shooter,505 Games,0.14,0.07,0.00,0.02,0.23
188,189,DiRT 4,2017.0,Racing,Codemasters,0.11,0.10,0.00,0.02,0.23
189,190,NBA Live 15,2014.0,Sports,Electronic Arts,0.18,0.02,0.00,0.02,0.22
190,191,F1 2016 (Codemasters),2016.0,Racing,Codemasters,0.09,0.12,0.00,0.02,0.22
191,192,Deadpool,2015.0,Action,Activision,0.17,0.03,0.00,0.02,0.22
192,193,The Amazing Spider-Man 2 (2014),2014.0,Action-Adventure,Activision,0.12,0.08,0.00,0.02,0.22
193,194,Kingdom Come: Deliverance,2018.0,Role-Playing,Deep Silver,0.14,0.06,0.00,0.02,0.22
194,195,Lords of the Fallen,2014.0,Role-Playing,Square Enix,0.10,0.10,0.00,0.02,0.22
195,196,Super Lucky's Tale,2017.0,Platform,Microsoft Studios,0.13,0.07,0.00,0.02,0.22
196,197,DiRT Rally,2016.0,Racing,Codemasters,0.12,0.08,0.00,0.02,0.21
197,198,Just Dance 2018,2017.0,Music,Ubisoft,0.15,0.04,0.00,0.02,0.21
198,199,Homefront: The Revolution,2016.0,Shooter,Deep Silver,0.10,0.09,0.00,0.02,0.21
199,200,State of Decay,2015.0,Action-Adventure,Microsoft Studios,0.14,0.05,0.00,0.02,0.21
200,201,NBA Live 18,2017.0,Sports,EA Sports,0.18,0.00,0.00,0.02,0.21
201,202,theHunter: Call of the Wild,2017.0,Shooter,Astragon,0.18,0.00,0.00,0.02,0.21
202,203,Sleeping Dogs,2014.0,Action-Adventure,Square Enix,0.10,0.09,0.00,0.02,0.20
203,204,Project CARS 2,2017.0,Racing,Namco Bandai Games,0.01,0.18,0.00,0.01,0.20
204,205,Batman: Return to Arkham,2016.0,Action,Warner Bros. Interactive Entertainment,0.12,0.06,0.00,0.02,0.20
205,206,Dishonored,2015.0,Action,Bethesda Softworks,0.13,0.05,0.00,0.02,0.19
206,207,One Piece: Burning Blood,2016.0,Fighting,Namco Bandai Games,0.11,0.07,0.00,0.02,0.19
207,208,Fantasia: Music Evolved,2014.0,Music,Disney Interactive Studios,0.14,0.03,0.00,0.02,0.19
208,209,Mirror's Edge 2,2016.0,Platform,Electronic Arts,0.11,0.06,0.00,0.02,0.19
209,210,Dance Central: Spotlight,NaN,Music,NaN,0.15,0.03,0.00,0.00,0.19
210,211,Naruto to Boruto: Shinobi Striker,2018.0,Action,Bandai Namco Games,0.17,0.00,0.00,0.02,0.19
211,212,XCOM 2,2016.0,Strategy,2K Games,0.15,0.02,0.00,0.02,0.19
212,213,F1 2017,2017.0,Racing,Koch Media,0.04,0.13,0.00,0.01,0.19
213,214,Shape Up,2014.0,Sports,Ubisoft,0.08,0.09,0.00,0.01,0.18
214,215,Cities: Skylines,2017.0,Simulation,Deep Silver,0.13,0.03,0.00,0.02,0.18
215,216,Sniper: Ghost Warrior 3,2017.0,Shooter,City Interactive,0.11,0.05,0.00,0.02,0.18
216,217,Project Spark (Working Title),2014.0,Misc,Microsoft Studios,0.11,0.05,0.00,0.02,0.17
217,218,Rush: A Disney Pixar Adventure,2017.0,Adventure,Microsoft Studios,0.15,0.00,0.00,0.02,0.17
218,219,Fighter Within,2013.0,Fighting,Ubisoft,0.08,0.07,0.00,0.01,0.17
219,220,Murdered: Soul Suspect,2014.0,Action-Adventure,Square Enix,0.08,0.07,0.00,0.01,0.17
220,221,Pac-Man Championship Edition 2 + Arcade Game S...,2016.0,Action,Namco Bandai Games,0.15,0.00,0.00,0.02,0.16
221,222,Angry Birds: Star Wars,2013.0,Puzzle,Activision,0.11,0.04,0.00,0.02,0.16
222,223,Little Nightmares,2017.0,Platform,Namco Bandai Games,0.12,0.03,0.00,0.02,0.16
223,224,The Walking Dead: Season One,2014.0,Adventure,Telltale Games,0.08,0.06,0.00,0.01,0.16
224,225,Wolfenstein: The Old Blood,2015.0,Shooter,Bethesda Softworks,0.07,0.07,0.00,0.01,0.15
225,226,Pro Evolution Soccer 2015,2014.0,Sports,Konami Digital Entertainment,0.04,0.10,0.00,0.01,0.15
226,227,Transformer: Rise of the Dark Spark,2014.0,Shooter,Activision,0.10,0.03,0.00,0.01,0.15
227,228,The Escapists 2,2017.0,Action,Sold Out,0.05,0.08,0.00,0.01,0.15
228,229,Transformers: Devastation,2015.0,Action,Activision,0.10,0.04,0.00,0.01,0.15
229,230,Spintires: MudRunner,2017.0,Simulation,Focus Home Interactive,0.11,0.02,0.00,0.01,0.15
230,231,DmC: Devil May Cry,2015.0,Action,Capcom,0.09,0.04,0.00,0.01,0.15
231,232,Attack on Titan (KOEI),2016.0,Action,Tecmo Koei,0.06,0.07,0.00,0.01,0.15
232,233,Tony Hawk's Pro Skater 5,2015.0,Sports,Activision,0.11,0.02,0.00,0.01,0.14
233,234,Naruto Shippuden: Ultimate Ninja Storm Legacy,2017.0,Fighting,Namco Bandai Games,0.11,0.02,0.00,0.01,0.14
234,235,The Walking Dead: Season Two,2014.0,Misc,Telltale Games,0.08,0.05,0.00,0.01,0.14
235,236,Resident Evil: Revelations 2,2015.0,Action,Capcom,0.10,0.02,0.00,0.01,0.14
236,237,Dishonored: Death of the Outsider,2017.0,Action,Bethesda Softworks,0.07,0.06,0.00,0.01,0.14
237,238,Ultimate Marvel vs. Capcom 3,2017.0,Fighting,Capcom,0.12,0.00,0.00,0.01,0.14
238,239,The Elder Scrolls Online: Morrowind,2017.0,MMO,Bethesda Softworks,0.09,0.03,0.00,0.01,0.14
239,240,Hasbro Family Fun Pack,2015.0,Misc,Ubisoft,0.10,0.02,0.00,0.01,0.13

## ## Filtering Xbox "Action Games" Released in 2014

In [11]:
f=xbox[(xbox["Year"]==2014)&(xbox["Genre"]=="Action")]

In [12]:
f

,Pos,Game,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global
0,1,Grand Theft Auto V,2014.0,Action,Rockstar Games,4.70,3.25,0.01,0.76,8.72
14,15,Assassin's Creed: Unity,2014.0,Action,Ubisoft,2.34,0.90,0.00,0.34,3.58
58,59,Middle-Earth: Shadow of Mordor,2014.0,Action,Warner Bros. Interactive Entertainment,0.77,0.52,0.01,0.12,1.42
66,67,Sunset Overdrive,2014.0,Action,Microsoft Studios,0.64,0.42,0.00,0.10,1.16
131,132,Thief 4,2014.0,Action,Square Enix,0.26,0.17,0.00,0.04,0.48
140,141,Lego Batman 3: Beyond Gotham,2014.0,Action,Warner Bros. Interactive Entertainment,0.24,0.17,0.00,0.04,0.44
299,300,Dynasty Warriors 8: Empires,2014.0,Action,Tecmo Koei,0.04,0.02,0.00,0.01,0.07
350,351,Terraria,2014.0,Action,505 Games,0.00,0.04,0.00,0.00,0.04
359,360,Warriors Orochi 3,2014.0,Action,Tecmo Koei,0.01,0.03,0.00,0.00,0.04
534,535,Scalebound,2014.0,Action,PlatinumGames,0.00,0.00,0.00,0.00,0.00
537,538,Lara Croft and the Temple of Osiris,2014.0,Action,Square Enix,0.00,0.00,0.00,0.00,0.00
546,547,The Legend of Korra (2014),2014.0,Action,Activision,0.00,0.00,0.00,0.00,0.00

## Filtering Xbox "Action Games" Released in 2014 & Publisher by "Rockstar Game"

In [8]:
f1=xbox[(xbox["Year"]==2014)&(xbox["Genre"]=="Action")&(xbox["Publisher"]=="Rockstar Games")]

In [9]:
f1

,Pos,Game,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global
0,1,Grand Theft Auto V,2014.0,Action,Rockstar Games,4.7,3.25,0.01,0.76,8.72

## Filtering Xbox Games Released from "2018" Onwards

In [28]:
f2=xbox[xbox["Year"]>=2018]

In [29]:
f2

,Pos,Game,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global
3,4,Red Dead Redemption 2,2018.0,Action-Adventure,Rockstar Games,3.76,1.47,0.0,0.54,5.77
41,42,Far Cry 5,2018.0,Action,Ubisoft,1.14,0.47,0.0,0.17,1.78
75,76,Sea of Thieves,2018.0,Action-Adventure,Microsoft Studios,0.60,0.27,0.0,0.09,0.96
77,78,Monster Hunter: World,2018.0,Action,Capcom,0.67,0.17,0.0,0.09,0.93
122,123,Dragon Ball Fighter Z,2018.0,Fighting,Namco Bandai Games,0.38,0.09,0.0,0.05,0.52
141,142,EA Sports UFC 3,2018.0,Sports,EA Sports,0.30,0.10,0.0,0.04,0.44
160,161,The Crew 2,2018.0,Racing,Ubisoft,0.20,0.10,0.0,0.03,0.33
185,186,A Way Out,2018.0,Action,Electronic Arts,0.17,0.05,0.0,0.02,0.24
193,194,Kingdom Come: Deliverance,2018.0,Role-Playing,Deep Silver,0.14,0.06,0.0,0.02,0.22
210,211,Naruto to Boruto: Shinobi Striker,2018.0,Action,Bandai Namco Games,0.17,0.00,0.0,0.02,0.19
246,247,Darksiders III,2018.0,Action,THQ Nordic,0.11,0.00,0.0,0.01,0.12
247,248,Vampyr,2018.0,Role-Playing,Focus Home Interactive,0.07,0.04,0.0,0.01,0.12
270,271,Sword Art Online: Fatal Bullet,2018.0,Role-Playing,Namco Bandai Games,0.09,0.00,0.0,0.01,0.10
273,274,We Happy Few,2018.0,Action-Adventure,Gearbox Software,0.07,0.01,0.0,0.01,0.09
276,277,Attack on Titan 2,2018.0,Action,Koei Tecmo,0.08,0.00,0.0,0.01,0.09
280,281,Monster Energy Supercross - The Official Video...,2018.0,Racing,Milestone S.r.l.,0.08,0.00,0.0,0.01,0.08
292,293,Metal Gear Survive,2018.0,Action,Konami Digital Entertainment,0.05,0.01,0.0,0.01,0.08
331,332,Extinction,2018.0,Action,Maximum Games,0.04,0.00,0.0,0.01,0.05
353,354,Don't Starve,2018.0,Adventure,505 Games,0.04,0.00,0.0,0.00,0.04
364,365,Pure Farming 2018,2018.0,Simulation,Techland,0.03,0.00,0.0,0.00,0.03
391,392,Shaq-Fu: A Legend Reborn,2018.0,Action,Wired Productions,0.02,0.00,0.0,0.00,0.02
438,439,Brothers in Arms: Furious 4,2019.0,Shooter,Ubisoft,0.00,0.00,0.0,0.00,0.00
447,448,Killer Instinct,2020.0,Misc,Microsoft Game Studios,0.00,0.00,0.0,0.00,0.00
464,465,Whore of the Orient,2020.0,Misc,Warner Bros. Interactive Entertainment,0.00,0.00,0.0,0.00,0.00
474,475,Halo 6,2020.0,Shooter,Microsoft Game Studios,0.00,0.00,0.0,0.00,0.00
481,482,Kingdom Hearts III,2019.0,Role-Playing,Square Enix,0.00,0.00,0.0,0.00,0.00
482,483,Black Tusk Studios Game,2020.0,Misc,Microsoft Game Studios,0.00,0.00,0.0,0.00,0.00
490,491,Fable Legends,2019.0,Role-Playing,Microsoft Studios,0.00,0.00,0.0,0.00,0.00
535,536,Crackdown 3,2019.0,Action,Microsoft Studios,0.00,0.00,0.0,0.00,0.00
601,602,Ace Combat 7: Skies Unknown,2019.0,Shooter,Bandai Namco Games,0.00,0.00,0.0,0.00,0.00
603,604,Metro Exodus,2019.0,Shooter,Deep Silver,0.00,0.00,0.0,0.00,0.00
604,605,Anthem,2019.0,Role-Playing,Electronic Arts,0.00,0.00,0.0,0.00,0.00
606,607,Moons Of Madness,2018.0,Role-Playing,Unknown,0.00,0.00,0.0,0.00,0.00
607,608,Iron Harvest,2018.0,Strategy,Unknown,0.00,0.00,0.0,0.00,0.00
608,609,Biomutant,2018.0,Action,THQ Nordic,0.00,0.00,0.0,0.00,0.00
609,610,Biomutant,2019.0,Action,THQ Nordic,0.00,0.00,0.0,0.00,0.00
612,613,Code Vein,2019.0,Action,Bandai Namco Entertainment,0.00,0.00,0.0,0.00,0.00

## Games that Published by "Rockstar Games"

In [4]:
g3=xbox[xbox["Publisher"]=="Rockstar Games"]

In [5]:
g3

,Pos,Game,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global
0,1,Grand Theft Auto V,2014.0,Action,Rockstar Games,4.70,3.25,0.01,0.76,8.72
3,4,Red Dead Redemption 2,2018.0,Action-Adventure,Rockstar Games,3.76,1.47,0.00,0.54,5.77
179,180,L.A. Noire,2017.0,Adventure,Rockstar Games,0.14,0.09,0.00,0.02,0.25

In [21]:
pwd

'C:\\Users\\Rahhal'